#include "pch.h"

#include "payload.h"

#define OGDEF(x) extern "C" void* og_##x; void* og_##x;
#define OGINIT(x, o) og_##x = GetProcAddress(hModuleOG, reinterpret_cast<LPCSTR>(o)); if(og_##x == nullptr) return FALSE;

#undef PlaySound

OGDEF(_0002);
OGDEF(mciExecute);
OGDEF(CloseDriver);
OGDEF(DefDriverProc);
OGDEF(DriverCallback);
OGDEF(DrvGetModuleHandle);
OGDEF(GetDriverModuleHandle);
OGDEF(OpenDriver);
OGDEF(PlaySound);
OGDEF(PlaySoundA);
OGDEF(PlaySoundW);
OGDEF(SendDriverMessage);
OGDEF(WOWAppExit);
OGDEF(auxGetDevCapsA);
OGDEF(auxGetDevCapsW);
OGDEF(auxGetNumDevs);
OGDEF(auxGetVolume);
OGDEF(auxOutMessage);
OGDEF(auxSetVolume);
OGDEF(joyConfigChanged);
OGDEF(joyGetDevCapsA);
OGDEF(joyGetDevCapsW);
OGDEF(joyGetNumDevs);
OGDEF(joyGetPos);
OGDEF(joyGetPosEx);
OGDEF(joyGetThreshold);
OGDEF(joyReleaseCapture);
OGDEF(joySetCapture);
OGDEF(joySetThreshold);
OGDEF(mciDriverNotify);
OGDEF(mciDriverYield);
OGDEF(mciFreeCommandResource);
OGDEF(mciGetCreatorTask);
OGDEF(mciGetDeviceIDA);
OGDEF(mciGetDeviceIDFromElementIDA);
OGDEF(mciGetDeviceIDFromElementIDW);
OGDEF(mciGetDeviceIDW);
OGDEF(mciGetDriverData);
OGDEF(mciGetErrorStringA);
OGDEF(mciGetErrorStringW);
OGDEF(mciGetYieldProc);
OGDEF(mciLoadCommandResource);
OGDEF(mciSendCommandA);
OGDEF(mciSendCommandW);
OGDEF(mciSendStringA);
OGDEF(mciSendStringW);
OGDEF(mciSetDriverData);
OGDEF(mciSetYieldProc);
OGDEF(midiConnect);
OGDEF(midiDisconnect);
OGDEF(midiInAddBuffer);
OGDEF(midiInClose);
OGDEF(midiInGetDevCapsA);
OGDEF(midiInGetDevCapsW);
OGDEF(midiInGetErrorTextA);
OGDEF(midiInGetErrorTextW);
OGDEF(midiInGetID);
OGDEF(midiInGetNumDevs);
OGDEF(midiInMessage);
OGDEF(midiInOpen);
OGDEF(midiInPrepareHeader);
OGDEF(midiInReset);
OGDEF(midiInStart);
OGDEF(midiInStop);
OGDEF(midiInUnprepareHeader);
OGDEF(midiOutCacheDrumPatches);
OGDEF(midiOutCachePatches);
OGDEF(midiOutClose);
OGDEF(midiOutGetDevCapsA);
OGDEF(midiOutGetDevCapsW);
OGDEF(midiOutGetErrorTextA);
OGDEF(midiOutGetErrorTextW);
OGDEF(midiOutGetID);
OGDEF(midiOutGetNumDevs);
OGDEF(midiOutGetVolume);
OGDEF(midiOutLongMsg);
OGDEF(midiOutMessage);
OGDEF(midiOutOpen);
OGDEF(midiOutPrepareHeader);
OGDEF(midiOutReset);
OGDEF(midiOutSetVolume);
OGDEF(midiOutShortMsg);
OGDEF(midiOutUnprepareHeader);
OGDEF(midiStreamClose);
OGDEF(midiStreamOpen);
OGDEF(midiStreamOut);
OGDEF(midiStreamPause);
OGDEF(midiStreamPosition);
OGDEF(midiStreamProperty);
OGDEF(midiStreamRestart);
OGDEF(midiStreamStop);
OGDEF(mixerClose);
OGDEF(mixerGetControlDetailsA);
OGDEF(mixerGetControlDetailsW);
OGDEF(mixerGetDevCapsA);
OGDEF(mixerGetDevCapsW);
OGDEF(mixerGetID);
OGDEF(mixerGetLineControlsA);
OGDEF(mixerGetLineControlsW);
OGDEF(mixerGetLineInfoA);
OGDEF(mixerGetLineInfoW);
OGDEF(mixerGetNumDevs);
OGDEF(mixerMessage);
OGDEF(mixerOpen);
OGDEF(mixerSetControlDetails);
OGDEF(mmDrvInstall);
OGDEF(mmGetCurrentTask);
OGDEF(mmTaskBlock);
OGDEF(mmTaskCreate);
OGDEF(mmTaskSignal);
OGDEF(mmTaskYield);
OGDEF(mmioAdvance);
OGDEF(mmioAscend);
OGDEF(mmioClose);
OGDEF(mmioCreateChunk);
OGDEF(mmioDescend);
OGDEF(mmioFlush);
OGDEF(mmioGetInfo);
OGDEF(mmioInstallIOProcA);
OGDEF(mmioInstallIOProcW);
OGDEF(mmioOpenA);
OGDEF(mmioOpenW);
OGDEF(mmioRead);
OGDEF(mmioRenameA);
OGDEF(mmioRenameW);
OGDEF(mmioSeek);
OGDEF(mmioSendMessage);
OGDEF(mmioSetBuffer);
OGDEF(mmioSetInfo);
OGDEF(mmioStringToFOURCCA);
OGDEF(mmioStringToFOURCCW);
OGDEF(mmioWrite);
OGDEF(mmsystemGetVersion);
OGDEF(sndPlaySoundA);
OGDEF(sndPlaySoundW);
OGDEF(timeBeginPeriod);
OGDEF(timeEndPeriod);
OGDEF(timeGetDevCaps);
OGDEF(timeGetSystemTime);
OGDEF(timeGetTime);
OGDEF(timeKillEvent);
OGDEF(timeSetEvent);
OGDEF(waveInAddBuffer);
OGDEF(waveInClose);
OGDEF(waveInGetDevCapsA);
OGDEF(waveInGetDevCapsW);
OGDEF(waveInGetErrorTextA);
OGDEF(waveInGetErrorTextW);
OGDEF(waveInGetID);
OGDEF(waveInGetNumDevs);
OGDEF(waveInGetPosition);
OGDEF(waveInMessage);
OGDEF(waveInOpen);
OGDEF(waveInPrepareHeader);
OGDEF(waveInReset);
OGDEF(waveInStart);
OGDEF(waveInStop);
OGDEF(waveInUnprepareHeader);
OGDEF(waveOutBreakLoop);
OGDEF(waveOutClose);
OGDEF(waveOutGetDevCapsA);
OGDEF(waveOutGetDevCapsW);
OGDEF(waveOutGetErrorTextA);
OGDEF(waveOutGetErrorTextW);
OGDEF(waveOutGetID);
OGDEF(waveOutGetNumDevs);
OGDEF(waveOutGetPitch);
OGDEF(waveOutGetPlaybackRate);
OGDEF(waveOutGetPosition);
OGDEF(waveOutGetVolume);
OGDEF(waveOutMessage);
OGDEF(waveOutOpen);
OGDEF(waveOutPause);
OGDEF(waveOutPrepareHeader);
OGDEF(waveOutReset);
OGDEF(waveOutRestart);
OGDEF(waveOutSetPitch);
OGDEF(waveOutSetPlaybackRate);
OGDEF(waveOutSetVolume);
OGDEF(waveOutUnprepareHeader);
OGDEF(waveOutWrite);


BOOL __stdcall DllMain
(
	HMODULE	hModule,
	DWORD	fdwReason,
	LPVOID	lpReserved
)
{
	HMODULE	hModuleOG;

	switch (fdwReason)
	{
	case DLL_PROCESS_ATTACH:
		hModuleOG						= LoadLibraryA("C:\\Windows\\system32\\winmm.dll");

		if(hModuleOG == nullptr){
			return FALSE;
		}
	
		OGINIT(_0002, 2);
		OGINIT(mciExecute, 3);
		OGINIT(CloseDriver, 4);
		OGINIT(DefDriverProc, 5);
		OGINIT(DriverCallback, 6);
		OGINIT(DrvGetModuleHandle, 7);
		OGINIT(GetDriverModuleHandle, 8);
		OGINIT(OpenDriver, 9);
		OGINIT(PlaySound, 10);
		OGINIT(PlaySoundA, 11);
		OGINIT(PlaySoundW, 12);
		OGINIT(SendDriverMessage, 13);
		OGINIT(WOWAppExit, 14);
		OGINIT(auxGetDevCapsA, 15);
		OGINIT(auxGetDevCapsW, 16);
		OGINIT(auxGetNumDevs, 17);
		OGINIT(auxGetVolume, 18);
		OGINIT(auxOutMessage, 19);
		OGINIT(auxSetVolume, 20);
		OGINIT(joyConfigChanged, 21);
		OGINIT(joyGetDevCapsA, 22);
		OGINIT(joyGetDevCapsW, 23);
		OGINIT(joyGetNumDevs, 24);
		OGINIT(joyGetPos, 25);
		OGINIT(joyGetPosEx, 26);
		OGINIT(joyGetThreshold, 27);
		OGINIT(joyReleaseCapture, 28);
		OGINIT(joySetCapture, 29);
		OGINIT(joySetThreshold, 30);
		OGINIT(mciDriverNotify, 31);
		OGINIT(mciDriverYield, 32);
		OGINIT(mciFreeCommandResource, 33);
		OGINIT(mciGetCreatorTask, 34);
		OGINIT(mciGetDeviceIDA, 35);
		OGINIT(mciGetDeviceIDFromElementIDA, 36);
		OGINIT(mciGetDeviceIDFromElementIDW, 37);
		OGINIT(mciGetDeviceIDW, 38);
		OGINIT(mciGetDriverData, 39);
		OGINIT(mciGetErrorStringA, 40);
		OGINIT(mciGetErrorStringW, 41);
		OGINIT(mciGetYieldProc, 42);
		OGINIT(mciLoadCommandResource, 43);
		OGINIT(mciSendCommandA, 44);
		OGINIT(mciSendCommandW, 45);
		OGINIT(mciSendStringA, 46);
		OGINIT(mciSendStringW, 47);
		OGINIT(mciSetDriverData, 48);
		OGINIT(mciSetYieldProc, 49);
		OGINIT(midiConnect, 50);
		OGINIT(midiDisconnect, 51);
		OGINIT(midiInAddBuffer, 52);
		OGINIT(midiInClose, 53);
		OGINIT(midiInGetDevCapsA, 54);
		OGINIT(midiInGetDevCapsW, 55);
		OGINIT(midiInGetErrorTextA, 56);
		OGINIT(midiInGetErrorTextW, 57);
		OGINIT(midiInGetID, 58);
		OGINIT(midiInGetNumDevs, 59);
		OGINIT(midiInMessage, 60);
		OGINIT(midiInOpen, 61);
		OGINIT(midiInPrepareHeader, 62);
		OGINIT(midiInReset, 63);
		OGINIT(midiInStart, 64);
		OGINIT(midiInStop, 65);
		OGINIT(midiInUnprepareHeader, 66);
		OGINIT(midiOutCacheDrumPatches, 67);
		OGINIT(midiOutCachePatches, 68);
		OGINIT(midiOutClose, 69);
		OGINIT(midiOutGetDevCapsA, 70);
		OGINIT(midiOutGetDevCapsW, 71);
		OGINIT(midiOutGetErrorTextA, 72);
		OGINIT(midiOutGetErrorTextW, 73);
		OGINIT(midiOutGetID, 74);
		OGINIT(midiOutGetNumDevs, 75);
		OGINIT(midiOutGetVolume, 76);
		OGINIT(midiOutLongMsg, 77);
		OGINIT(midiOutMessage, 78);
		OGINIT(midiOutOpen, 79);
		OGINIT(midiOutPrepareHeader, 80);
		OGINIT(midiOutReset, 81);
		OGINIT(midiOutSetVolume, 82);
		OGINIT(midiOutShortMsg, 83);
		OGINIT(midiOutUnprepareHeader, 84);
		OGINIT(midiStreamClose, 85);
		OGINIT(midiStreamOpen, 86);
		OGINIT(midiStreamOut, 87);
		OGINIT(midiStreamPause, 88);
		OGINIT(midiStreamPosition, 89);
		OGINIT(midiStreamProperty, 90);
		OGINIT(midiStreamRestart, 91);
		OGINIT(midiStreamStop, 92);
		OGINIT(mixerClose, 93);
		OGINIT(mixerGetControlDetailsA, 94);
		OGINIT(mixerGetControlDetailsW, 95);
		OGINIT(mixerGetDevCapsA, 96);
		OGINIT(mixerGetDevCapsW, 97);
		OGINIT(mixerGetID, 98);
		OGINIT(mixerGetLineControlsA, 99);
		OGINIT(mixerGetLineControlsW, 100);
		OGINIT(mixerGetLineInfoA, 101);
		OGINIT(mixerGetLineInfoW, 102);
		OGINIT(mixerGetNumDevs, 103);
		OGINIT(mixerMessage, 104);
		OGINIT(mixerOpen, 105);
		OGINIT(mixerSetControlDetails, 106);
		OGINIT(mmDrvInstall, 107);
		OGINIT(mmGetCurrentTask, 108);
		OGINIT(mmTaskBlock, 109);
		OGINIT(mmTaskCreate, 110);
		OGINIT(mmTaskSignal, 111);
		OGINIT(mmTaskYield, 112);
		OGINIT(mmioAdvance, 113);
		OGINIT(mmioAscend, 114);
		OGINIT(mmioClose, 115);
		OGINIT(mmioCreateChunk, 116);
		OGINIT(mmioDescend, 117);
		OGINIT(mmioFlush, 118);
		OGINIT(mmioGetInfo, 119);
		OGINIT(mmioInstallIOProcA, 120);
		OGINIT(mmioInstallIOProcW, 121);
		OGINIT(mmioOpenA, 122);
		OGINIT(mmioOpenW, 123);
		OGINIT(mmioRead, 124);
		OGINIT(mmioRenameA, 125);
		OGINIT(mmioRenameW, 126);
		OGINIT(mmioSeek, 127);
		OGINIT(mmioSendMessage, 128);
		OGINIT(mmioSetBuffer, 129);
		OGINIT(mmioSetInfo, 130);
		OGINIT(mmioStringToFOURCCA, 131);
		OGINIT(mmioStringToFOURCCW, 132);
		OGINIT(mmioWrite, 133);
		OGINIT(mmsystemGetVersion, 134);
		OGINIT(sndPlaySoundA, 135);
		OGINIT(sndPlaySoundW, 136);
		OGINIT(timeBeginPeriod, 137);
		OGINIT(timeEndPeriod, 138);
		OGINIT(timeGetDevCaps, 139);
		OGINIT(timeGetSystemTime, 140);
		OGINIT(timeGetTime, 141);
		OGINIT(timeKillEvent, 142);
		OGINIT(timeSetEvent, 143);
		OGINIT(waveInAddBuffer, 144);
		OGINIT(waveInClose, 145);
		OGINIT(waveInGetDevCapsA, 146);
		OGINIT(waveInGetDevCapsW, 147);
		OGINIT(waveInGetErrorTextA, 148);
		OGINIT(waveInGetErrorTextW, 149);
		OGINIT(waveInGetID, 150);
		OGINIT(waveInGetNumDevs, 151);
		OGINIT(waveInGetPosition, 152);
		OGINIT(waveInMessage, 153);
		OGINIT(waveInOpen, 154);
		OGINIT(waveInPrepareHeader, 155);
		OGINIT(waveInReset, 156);
		OGINIT(waveInStart, 157);
		OGINIT(waveInStop, 158);
		OGINIT(waveInUnprepareHeader, 159);
		OGINIT(waveOutBreakLoop, 160);
		OGINIT(waveOutClose, 161);
		OGINIT(waveOutGetDevCapsA, 162);
		OGINIT(waveOutGetDevCapsW, 163);
		OGINIT(waveOutGetErrorTextA, 164);
		OGINIT(waveOutGetErrorTextW, 165);
		OGINIT(waveOutGetID, 166);
		OGINIT(waveOutGetNumDevs, 167);
		OGINIT(waveOutGetPitch, 168);
		OGINIT(waveOutGetPlaybackRate, 169);
		OGINIT(waveOutGetPosition, 170);
		OGINIT(waveOutGetVolume, 171);
		OGINIT(waveOutMessage, 172);
		OGINIT(waveOutOpen, 173);
		OGINIT(waveOutPause, 174);
		OGINIT(waveOutPrepareHeader, 175);
		OGINIT(waveOutReset, 176);
		OGINIT(waveOutRestart, 177);
		OGINIT(waveOutSetPitch, 178);
		OGINIT(waveOutSetPlaybackRate, 179);
		OGINIT(waveOutSetVolume, 180);
		OGINIT(waveOutUnprepareHeader, 181);
		OGINIT(waveOutWrite, 182);
		break;
	}

	return DllMain_Payload(hModule, fdwReason, lpReserved);
}
